name=MiP Power Up - D1 mini
version=2.0.1
author=Samuel Trassare <tiogaplanet@users.noreply.github.com>
maintainer=Samuel Trassare <tiogaplanet@users.noreply.github.com>
sentence=Control the WowWee MiP robot from a WeMos D1 mini (ESP8266).
paragraph=This library, together with the matching adapter board, lets you connect a WeMos D1 mini to the MiP robot via serial. It turns MiP into a powerful Internet-connected robot with full access to motion, sensors, sound, LEDs, and more.
category=Device Control
url=https://github.com/Tiogaplanet/MPU_D1_mini_lib
architectures=esp8266
includes=MiP_Power_Up_-_D1_mini.h